project:
  type: website
  output-dir: docs
  preview:
      port: 4444

lang: pt

website: 
  favicon: "ima/FS2.png"
  site-url: ""
  open-graph: true
  page-navigation: true
  search: TRUE
  google-analytics: "G-8L8YC0LJJY"
  page-footer: 
    left: "Website made with quarto Â© 2023 by Gustavo Frosi is licensed under CC BY-SA 4.0."
    right: 
      - icon: github
        href: https://github.com/FGu5tav0
      - icon: envelope
        href: "mailto:gustavofrosi@hotmail.com"
    center: <img src="ima/FS.png" width="25" height="25" >
    
    
    
  title: "Gustavo Frosi"
  navbar:
    logo: "ima/FS2.png"
    left: 
      - text: "CV"
        href: CV/index.qmd
      - text: "Projetos"
        href: projetos.qmd
      - text: "Posts"
        href: recap.qmd

  # sidebar:
  #   - id: Projetos
  #     title: "Projetos"
  #     style: "docked"
  #     background: light
  #     collapse-level: 2
  #     contents: 
  #       - projetos.qmd
  #       - projetos/um.qmd
  #       - projetos/dois.qmd
  #       # navigation items

format:
  html:
    theme:
      light: [lux, tema.scss]
      # dark: [lux, tema_dark.scss]
    # css: styles.css
    toc: true

execute:
  freeze: false


# comments:
#   giscus:
#     repo: FGu5tav0

