project:
  type: website
  output-dir: docs
  preview:
      port: 4444

lang: pt

website: 
  back-to-top-navigation: true
  favicon: "ima/FS2.png"
  site-url: ""
  open-graph: true
  page-navigation: true
  search: false
  google-analytics: "G-8L8YC0LJJY"
  cookie-consent:
    type: express
    prefs-text: "Cookies"
  page-footer: 
    left: "Website made with quarto © 2024 by Gustavo Frosi is licensed under CC BY-SA 4.0."
    right: 
      - icon: github
        href: https://github.com/FGu5tav0
      - icon: envelope
        href: "mailto:gustavofrosi@hotmail.com"
    center: <img src="ima/FS.png" width="25" height="25" >
    
    
    
  title: "Gustavo Frosi"
  navbar:
    logo: "ima/FS.png"
    left: 
      - text: "Formação"
        href: formacao.qmd
      - text: "CV"
        href: CV/index.qmd
      - text: "Projetos"
        href: projetos.qmd
      - text: "Trabalhos Científicos"
        menu:
          - href: artigos.qmd
            text: "Artigos"
          - href: resumos.qmd
            text: "Resumos"
          # - artigos.qmd
          # - trabalhos_pos/resumos.qmd
      - text: "Posts"
        href: recap.qmd

  # sidebar:
  # - id: trabalhos
  #   title: "Trabalho Científico"
  #   # style: "docked"
  #   # background: light
  #   # collapse-level: 4
  #   contents:
  #     - text: "Artigos"
  #       href: trabalhos_pos/artigos.qmd
  #     - text: "Resumos e apresentações"
  #       href: CV/index.qmd
  #       # href: trabalhos_pos/resumos.qmd

format:
  html:
    theme:
      light: [litera, tema.scss]
      # dark: [litera]
    # css: styles.css
    toc: true

execute:
  freeze: false


# comments:
#   giscus:
#     repo: FGu5tav0

